- name: Install the gamecreditsd client prerequisites
  apt: name={{item}} update_cache=yes state=present
  with_items:
    - libexempi3
    - libpq-dev
    - python-dev
    - libffi-dev
    - libncurses5-dev
    - libjpeg-dev
    - zlib1g-dev
    - libtiff5
    - ntp
    - build-essential
    - libssl-dev
    - libdb-dev
    - libdb++-dev
    - libboost-all-dev
    - libqrencode-dev
    - autoconf
    - automake
    - pkg-config
    - unzip
    - libevent-dev    
    - libtool
  become: True

- name: Clone the GameCredits repository
  git: >
    dest=~/gamecredits 
    repo=https://github.com/gamecredits-project/GameCredits

- name: Run autogen
  command: ./autogen.sh
  args:
    chdir: ~/gamecredits

# Ubuntu 16.04 flags, without these the compilation fails
- name: Run configure
  command: "./configure --with-incompatible-bdb"
  args:
    chdir: ~/gamecredits

- name: Compile the wallet
  command: make
  args:
    chdir: ~/gamecredits
    creates: ~/gamecredits/scr/gamecreditsd
  ignore_errors: yes
  
- name: Create the data directory
  file: path=~/.gamecredits state=directory

- name: Copy the default gamecredits.conf file
  template: src=templates/gamecredits.conf dest=~/.gamecredits/gamecredits.conf

- name: Create the logs directory
  file: path=/var/log/gamecreditsd state=directory
  become: True

- name: Copy the supervisor startup file
  template: src=templates/gamecreditsd-supervisor.conf dest=/etc/supervisor/conf.d/gamecredits-supervisor.conf
  become: True

- name: Update supervisorctl
  command: "supervisorctl update"
  become: True

- name: Restart the gamecreditsd service
  supervisorctl: name=gamecreditsd state=restarted
  become: True

- name: Get supervisorctl status
  command: "supervisorctl status"
  register: supervisor_output
  become: True

- name: Debug
  debug: var=supervisor_output

- name: Fail the play if the previous command did not succeed
  fail: msg="Some of the supervisor services failed to start"
  when: "'FATAL' in supervisor_output.stdout or 'BACKOFF' in supervisor_output.stdout"

- name: Enable the gamecreditsd client ports in ufw
  ufw: rule=allow port={{ item }}
  with_items:
    - 8332
    - 8333
  become: True
