# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  # Create the blockexplorer VM
  config.vm.define "blockexplorer" do |blockexplorer|
    blockexplorer.vm.box = "thedivic/gamecredits"
    blockexplorer.vm.synced_folder "..", "/exploder"
    # blockexplorer.vm.synced_folder "../../gamecredits-pip", "/gamecredits-pip"



    blockexplorer.vm.network "forwarded_port", guest: 80, host: 8080
    blockexplorer.vm.network "forwarded_port", guest: 81, host: 8081

    blockexplorer.vm.provider "virtualbox" do |vb|
      # vb.gui = true
      vb.memory = "8096"
      vb.cpus = 2
    end
  end
end
