# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Use the same key for each machine
  config.ssh.insert_key = false

  # Create the blockexplorer VM
  config.vm.define "blockexplorer" do |blockexplorer|
    blockexplorer.vm.box = "thedivic/gamecredits"
    blockexplorer.vm.synced_folder "..", "/code"
    blockexplorer.vm.synced_folder "C:/Users/divic/Desktop/Work/GameCredits/gamecredits-pip", "/gamecredits-pip"
    blockexplorer.vm.network "forwarded_port", guest: 5000, host: 8080

    blockexplorer.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      # vb.gui = true
      vb.memory = "2048"
      vb.cpus = 2
    end
  end
end
